demos/ujs-classroom/config/routes.rb
Rails.application.routes.draw do
  root 'application#index'
  devise_for :users

  post 'student/assign' => 'application#student_assign_course', as: :student_assign_course
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

demos/ujs-classroom/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

demos/ujs-classroom/app/models/course.rb
class Course < ApplicationRecord
  belongs_to :instructor, class_name: 'User'
  has_many :course_attendees
  has_many :students, through: :course_attendees, source: :user

  def self.recent_courses
    # where(created_at: (Time.now-) )
  end
end

demos/ujs-classroom/app/models/course_attendee.rb
class CourseAttendee < ApplicationRecord
  belongs_to :course
  belongs_to :user
end

demos/ujs-classroom/app/models/user.rb
class User < ApplicationRecord
  has_many :course_attendees
  has_many :courses, through: :course_attendees

  enum role: [:student, :instructor, :staff]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def print_courses
    courses.map{|c| c.name}.join(', ')
  end
end

demos/ujs-classroom/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def index
    @students = User.where role: :student
    @instructors = User.where role: :instructor
    @courses = Course.all
  end

  def student_assign_course
    @student = User.find params[:user_id]
    @course = Course.find params[:course_id]
    @student.courses << @course
  end
end

demos/ujs-classroom/app/helpers/application_helper.rb
module ApplicationHelper
end

demos/ujs-classroom/app/views/application/index.html.erb
	<h2>Assign Students to Course</h2>
	<table>
		<tbody>
			<tr>
				<th>Student</th>
				<th>Course</th>
				<th>Assign</th>
			</tr>
	<% @students.each do |user| %>

			<tr id="user_row_<%= user.id %>">
				<%= form_tag student_assign_course_path, method: :post, remote: true do %>
				<%= hidden_field_tag :user_id, user.id %>
				<td><%= user.fname %></td>
				<td class="course"><%= user.print_courses %></td>
				<td><%= collection_select nil, :course_id, @courses, :id, :name, {prompt: true}, {onchange: "Rails.fire(document.querySelector('#user_row_#{user.id} form'), 'submit');"} %></td>
			<% end %>
	<% end %>
		</tbody>
	</table>

	<!-- <h2>Assign Instructor to Course</h2> -->
	<% @courses.each do |course| %>

	<% end %>

demos/ujs-classroom/app/views/application/student_assign_course.js.erb
document.querySelector("#user_row_<%= @student.id %> .course").innerText = "<%= @student.print_courses %>";

demos/ujs-classroom/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UjsClassroom</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/icon?family=Material+Icons" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  	<header id="status">
	  	<p class="notice"><%= notice %></p>
			<p class="alert"><%= alert %></p>
		</header>
    <%= yield %>
  </body>
</html>